### ISSUE TITLE
Move some features out of Beta in documentation

### ISSUE THREAD

**Issue by privatemaker** [decaporg/decap-cms#7040] opened 2024-01-18 00:03 UTC
There are multiple really great features under [Beta Features](https://decapcms.org/docs/beta-features/) in Decap, but the only way to find them is to feel adventurous and navigate there in the documentation. 

Many of these nice features have been available and some are stable for awhile now. Do some of them have bugs? Sure. Just like many other parts of Decap, just like a lot of software.

Is there a process to determine when one of these features is no longer in `Beta` and thus moved to be alongside it's more logical place within the documentation?

It seems this should be discussed and some things probably moved out of `Beta` status 😄

**Comment by privatemaker** [comment] 2024-01-18 14:48
Yeah that seems correct to me @martinjagodic I can try sending a pull-req if there is more consensus to do this and no-one else wants to!

**Comment by martinjagodic** [comment] 2024-01-18 14:53
A PR would be amazing. I am ready to help once you open it. 

Note that this is actually a duplicate of #4608. I will close the older one as activity is happening here.

**Comment by privatemaker** [comment] 2024-01-23 17:36
While working on #7051 I realized the changes made in these pull-reqs are likely to leave a lot of old links on the internet such as: `/docs/beta-features/#working-with-a-local-git-repository` which will show 404 pages and thus confused users.

Before this is marked as closed, this should be looked into. I am not a Gatsby developer, but AFAICT from their [redirect documentation](https://www.gatsbyjs.com/docs/how-to/cloud/working-with-redirects-and-rewrites/) it does not mention handling links with `/url/path/#anchor-tag`

**Comment by martinjagodic** [comment] 2024-01-24 07:13
I agree. Maybe we could use this? https://www.gatsbyjs.com/plugins/gatsby-plugin-anchor-links/

**Closed** 2024-01-30 11:12 UTC
Labels: area: docs, pinned, type: feature
