### ISSUE TITLE
Error: Cannot get the start point in the node at path [7] because it has no start text node.

### ISSUE THREAD

**Issue by mohab-sameh** [decaporg/decap-cms#7218] opened 2024-05-29 23:12 UTC
**Describe the bug**

The CMS crashes when an item is deleted in a rich text field.

**To Reproduce**

Delete an item in a rich text field.

**Expected behavior**

Bullet list item should be deleted w/o crashes.

**Screenshots**

<img width="1512" alt="Screenshot 2024-05-30 at 2 11 14 AM" src="https://github.com/decaporg/decap-cms/assets/37941642/d2abbe70-439d-4c46-8101-90c7eccb990f">

**Applicable Versions:**
 - Decap CMS version: `decap-cms@3.1.10`
 - Git provider: `git-gateway`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:126.0) Gecko/20100101 Firefox/126.0`

**CMS configuration**
```
backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  branch: master
media_folder: theme/assets/images
public_folder: /assets/images
collections:
  - name: pages
    label: Pages
    identifier_field: title
    extension: md
    create: false
    delete: false
    slug: "{{slug}}"
    editor:
      preview: false
    folder: cms/pages
    fields:
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
      - label: Layout
        widget: hidden
        name: layout
        default: "{{slug}}.html"
      - label: Seo
        name: seo
        widget: object
        collapsed: true
        fields:
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: string
            required: false
          - label: No index
            name: noindex
            widget: boolean
            default: false
            required: false
          - label: Open Graph Title
            name: og:title
            widget: string
            required: false
          - label: Open Graph Image
            name: og:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Twitter Title
            name: twitter:title
            widget: string
            default: summary
            required: false
          - label: Twitter Card
            name: twitter:card
            widget: string
            default: summary
            required: false
          - label: Twitter Site
            name: twitter:site
            widget: string
            required: false
          - label: Twitter Creator
            name: twitter:creator
            widget: string
            required: false
          - label: Twitter Image
            name: twitter:image
            widget: image
            required: false
            media_library:
              config:
                multiple: false
          - label: Additional HTML tags
            name: additional_tags
            widget: text
            required: false
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    view_groups: []
  - name: articles
    label: Articles
    folder: cms/articles
    create: true
    identifier_field: name
    extension: md
    slug: "{{slug}}"
    fields:
      - hint: ""
        name: title
        label: Name
        widget: string
        required: true
      - hint: ""
        name: created-on
        label: Created On
        widget: datetime
        required: false
      - hint: ""
        name: updated-on
        label: Updated On
        widget: datetime
        required: false
      - hint: ""
        name: published-on
        label: Published On
        widget: datetime
        required: false
      - label: Editor's Note
        name: body
        widget: markdown
        required: false
      - hint: ""
        name: f_article-description
        label: Article Description
        widget: text
        required: false
      - hint: ""
        name: f_article-image
        label: Article Image
        widget: object
        required: false
        fields:
          - hint: ""
            name: url
            label: Image
            widget: image
            required: false
            allow_multiple: false
          - hint: Image Alt
            name: alt
            label: alt
            widget: st
...

**Comment by mohab-sameh** [comment] 2024-06-03 16:19
@LHSnow Yes. Looks like it's the same. Really blocking issue.

**Comment by martinjagodic** [comment] 2024-06-13 13:38
Closing as duplicate of #7123

**Closed by martinjagodic** 2024-06-13 13:38 UTC
