### ISSUE TITLE
Cursor in description textarea when trying to edit text it jumps to the end of text

### ISSUE THREAD

**Issue by keogh** [decaporg/decap-cms#6557] opened 2022-09-16 13:35 UTC
**Describe the bug**
In the netlify-cms admin provided by netlify under the `/admin` url when adding a new post/blog/entry and type text in the "description" textarea the cursor always goes to the last caracter. So if you try to edit some text in the middle of the curpus after you type the first letter the cursor jumps right into the end of the text.

**To Reproduce**
* Go to your `/admin` site
* New Entry
* Go to Description textarea, either rich text or markdown
* Type some text
* Move your cursor to any previously typed text
* Type anything
* The cursor goes to the end of text instead of staying where it should

**Expected behavior**
* The user should be able to edit previously typed text

**Screenshots**

https://user-images.githubusercontent.com/417939/190650484-232a74cb-90e2-48cf-af38-0eed2fca42fd.mov

**Applicable Versions:**
- Netlify CMS APP: 2.15.52
- Netlify CMS Core: 2.51.1
- OS: MacOS: 12.5
- Browser version: Chrome 105

<img width="231" alt="Screen Shot 2022-09-16 at 7 32 58" src="https://user-images.githubusercontent.com/417939/190651283-251e2c38-4a7f-4778-ad23-e1e31aa41529.png">

**Comment by wing5wong** [comment] 2022-09-18 21:19
Turned up to note the same issue.
Extremely annoying and, while it can be worked around, makes the field practically unusable.

**Comment by falcon-Z** [comment] 2022-09-19 12:02
I experience the same issue as well. Also noticed few more issues.
* When adding an emoji, the text cursor moves before the emoji and cannot be placed at the end after the emoji. However, when trying to add text before the emoji after each keypress cursor jumps to the end of the line
* Autocorrect has no effect. I use Microsoft editor and as i try to replace a mistaken word with its correction, it has no effect but, just highlights the word without making any changes
* I also had a weird experience wich i can't seem to reproduce. I kept trying to edit a word in the middle of the sentence (unable to trace actual steps) and at some point, the same sentence kept repeating itself  everytime i type a charecter and the same behaviour persisted when i delete a charecter. 

P.S. All these issues occur only within the `Markdown` widget

**Comment by rzzo** [comment] 2022-09-19 14:46
This looks like a duplicate to: https://github.com/netlify/netlify-cms/issues/6556

**Comment by fymmot** [comment] 2022-09-21 15:00
I am also having the same issue. 

I am running:
```
netlify-cms-app 2.15.72
netlify-cms-core 2.55.2
netlify-cms 2.10.192
```

**Comment by tremby** [comment] 2022-09-28 20:06
I just had a report from a user of the same issue. Says she's using Chrome, latest version, and sees the issue on both of her laptops.

**Comment by fymmot** [comment] 2022-09-29 11:27
This workaround solved the issue for me:

https://github.com/netlify/netlify-cms/issues/5092#issuecomment-1246525269

**Comment by dotspencer** [comment] 2022-11-28 04:10
Here's the quick fix from the link above.

Add the following css to the Netlify CMS admin html file (normally `admin/index.html`)

```
<style>
[data-slate-editor] { 
    -webkit-user-modify: read-write !important; 
}
</style>
```

**Comment by tremby** [comment] 2023-04-26 21:12
Still needs fixing.

**Comment by martinjagodic** [comment] 2023-08-24 09:10
This is fixed in Decap 3

**Closed by martinjagodic** 2023-08-24 09:10 UTC
Labels: area: extensions/widgets/markdown, type: bug
