### ISSUE TITLE
(re)generated TOML file doesn't have a new newline end of file

### ISSUE THREAD

**Issue by razonyang** [decaporg/decap-cms#6994] opened 2023-11-25 15:04 UTC
**Is your feature request related to a problem? Please describe.**

I'd like to put a newline at the end of file, but after modifying an entry, that line was removed.

Related PR https://github.com/hbstack/site/pull/723/files.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sonvir249** [comment] 2023-11-27 09:49
I am working on this.

**Comment by sonvir249** [comment] 2023-11-27 10:01
@razonyang I apologize for any confusion. I've identified a newline at the end of the file in the specified https://github.com/decaporg/decap-cms/blob/master/netlify.toml. Please correct me if I'm wrong.

**Comment by razonyang** [comment] 2023-11-27 10:06
@sonvir249 Thanks for taking time on this, I want to add the newline at end of line of TOML files generated by Decap CMS, not source code of Decap CMS.

Those https://github.com/hbstack/site/pull/723/files are generated by Decap CMS, but without newline at the end, is there existing an option for this?

**Comment by martinjagodic** [comment] 2023-11-29 08:35
@razonyang this is a known issue, so I am closing this as a duplicate of #1382.

**Closed by martinjagodic** 2023-11-29 08:35 UTC
Labels: type: feature
