### ISSUE TITLE
Error: Cannot find a descendant at path [6,2,0,2] in node: {"children":[{"type":"heading-two","ch...

### ISSUE THREAD

**Issue by therealwacs** [decaporg/decap-cms#7251] opened 2024-07-10 11:55 UTC
<img width="1672" alt="Снимок экрана 2024-07-09 в 18 27 47" src="https://github.com/decaporg/decap-cms/assets/74868958/d6585ab1-aa2f-410f-8db5-640dbd9d1cf2">

**Applicable Versions:**
 - Decap CMS version: `decap-cms@3.1.2`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`

**CMS configuration**
```
backend:
  name: github
  repo: community-phone-company/website
  branch: add-new-pages-posts
  site_domain: https://www.communityphone.org
media_folder: public/img/blog/images
public_folder: /img/blog/images
collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    fields:
      - label: Title
        name: title
        widget: string
      - label: Excerpt
        name: excerpt
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Featured
        name: featured
        widget: boolean
        default: false
      - label: Thumbnail
        name: thumbnail
        widget: image
        choose_url: true
        media_library:
          config:
            multiple: false
        required: false
      - label: Meta Title
        name: metaTitle
        widget: string
        required: false
      - label: Meta Description
        name: metaDescription
        widget: string
        required: false
      - label: Meta Keywords
        name: keywords
        widget: string
        required: false
      - label: Publish Date
        name: date
        widget: datetime
      - label: CTA Group
        name: ctaGroup
        widget: select
        options:
          - consumer
          - business
        default: consumer
      - label: Tags
        name: tags
        widget: relation
        collection: tags
        search_fields:
          - title
        value_field: title
        display_fields:
          - title
        multiple: true
        required: false
      - label: Authors
        name: authors
        widget: list
        default: []
        field:
          label: Author
          name: author
          widget: select
          options:
            - ellie
            - james
            - mark
            - logan
        required: false
      - label: Editors
        name: editors
        widget: list
        default: []
        field:
          label: Editor
          name: editor
          widget: select
          options:
            - ellie
            - james
            - mark
            - logan
        required: false
      - label: Updated At
        name: updatedAt
        widget: datetime
        required: false
      - label: Index
        name: index
        widget: boolean
        default: true
      - label: Sidebar Visible
        name: isSidebarVisible
        widget: boolean
        default: true
      - label: See All Posts Visible
        name: isSeeAllPostsVisible
        widget: boolean
        default: true
      - label: Bottom CTA Visible
        name: isBottomCtaVisible
        widget: boolean
        default: true
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - date
      - commit_author
    view_filters: []
    view_groups: []
  - name: tags
    label: Tags
    folder: blog/tags
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - label: Title
        name: title
        widget: string
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - commit_author
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Comment by martinjagodic** [comment] 2024-08-05 08:08
Duplicate of #7123

**Closed by martinjagodic** 2024-08-05 08:08 UTC
