### ISSUE TITLE
DecapCMS 3.0/GatsbyJS React 18 error

### ISSUE THREAD

**Issue by Isaac-Tait** [decaporg/decap-cms#6883] opened 2023-08-24 19:09 UTC
Congratulations on the DecapCMS 3.0 release! 

Following the [install](https://decapcms.org/docs/gatsby/) guidelines when I run `npm install --save decap-cms-app gatsby-plugin-netlify-cms` I get the following error message:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: royal-ridges-retreat@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.4 || ^17.0.0" from decap-cms-app@3.0.3
npm ERR! node_modules/decap-cms-app
npm ERR!   decap-cms-app@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

My repo is fully up to date, if I try to downgrade React to 17 then I get cascading error messages. Going down that rabbit hole is just too much work.

**Describe the bug**
DecapCMS appears to not be compatible with React 18

**Expected behavior**
When I install DecapCMS it should be compatible with React18

#6544

**Comment by martinjagodic** [comment] 2023-08-25 06:52
@Isaac-Tait unfortunately Decap is not yet upgraded to React 18 :( This is a priority issue for us so stay tuned for near future releases.

I am closing this task as duplicate of #6499

**Closed by martinjagodic** 2023-08-25 06:52 UTC
Labels: type: bug

**Comment by Isaac-Tait** [comment] 2023-08-25 19:52
@martinjagodic Awesome! Can't wait 😎
