### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child o...

### ISSUE THREAD

**Issue by Biboswan** [decaporg/decap-cms#7194] opened 2024-05-01 12:55 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Decap CMS version: `decap-cms@3.1.10`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`

**CMS configuration**
```
backend:
  name: github
  repo: Biboswan/rbanquets
  branch: main
  base_url: https://rbanquets.com/api
media_folder: public/img
public_folder: img
collections:
  - name: pages
    label: Pages
    files:
      - label: About Us
        name: about us
        file: content/about-us.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
    publish: true
    type: file_based_collection
    sortable_fields:
      - commit_date
      - commit_author
    view_filters: []
    view_groups: []
publish_mode: simple
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**

**Comment by hkbertoson** [comment] 2024-05-02 15:12
I also opened one for this error as well. #7176

**Comment by mohab-sameh** [comment] 2024-05-29 23:08
@demshy Same thing with me. I can consistently reproduce this when deleting an item in a bullet list in a rich text element.

**Comment by martinjagodic** [comment] 2024-08-05 08:09
Duplicate of #6965

**Closed by martinjagodic** 2024-08-05 08:09 UTC
