### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child o...

### ISSUE THREAD

**Issue by hkbertoson** [decaporg/decap-cms#7176] opened 2024-04-11 22:44 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Applicable Versions:**
 - Decap CMS version: `decap-cms@3.1.9`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36`

**CMS configuration**
```
local_backend: true
backend:
  name: github
  branch: dev
  repo: repo
  site_domain: domain
  base_url: url
  auth_endpoint: oauth
  squash_merges: true
media_folder: src/assets/img
media_library:
  name: cloudinary
  config:
    cloud_name: cloudname
    api_key: api_key
public_folder: src/assets/img
publish_mode: editorial_workflow
collections:
  - name: global
    label: Settings
    folder: src/content/global
    extension: yaml
    create: false
    fields:
      - label: Site Title
        name: title
        widget: string
      - label: Site Description
        name: description
        widget: string
      - label: Main Page Information
        name: mainPage
        widget: text
      - label: Image Slider
        name: imageSlider
        widget: list
        fields:
          - label: Image
            name: image
            widget: image
          - label: Alt Text
            name: alt
            widget: string
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - commit_author
      - description
    view_filters: []
    view_groups: []
  - name: locations
    label: Locations
    folder: src/content/location
    extension: json
    create: false
    delete: false
    fields:
      - label: Name
        name: name
        widget: string
      - label: Slug
        name: slug
        widget: string
      - label: Ages Accepted
        name: ages_accepted
        widget: string
      - label: Hours
        name: hours
        widget: string
      - label: Email
        name: email
        widget: string
      - label: Phone
        name: phone
        widget: string
      - label: Link
        name: link
        widget: string
      - label: description
        name: description
        widget: text
      - label: Address
        name: address
        widget: text
      - label: Image
        name: image
        widget: image
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - name
      - name
      - description
    view_filters: []
    view_groups: []
  - name: careers
    label: Careers
    folder: src/content/currentOpenings
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: description
        name: description
        widget: text
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - commit_author
      - description
    view_filters: []
    view_groups: []
  - name: about
    label: About
    folder: src/content/about
    identifier_field: title
    create: false
    delete: false
    fields:
      - label: Title
        name: title
        widget: string
      - label: About us
        name: about
        widget: text
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - commit_author
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
isFetching: false
error: null

```

**Additional context**

**Comment by martinjagodic** [comment] 2024-06-13 13:36
Closing as duplicate of #7194

**Closed by martinjagodic** 2024-06-13 13:36 UTC
