### ISSUE TITLE
Please replace with a clear and descriptive title

### ISSUE THREAD

**Issue by ahnslab** [decaporg/decap-cms#6826] opened 2023-06-30 03:31 UTC
Hello. I’m so interested in this service. (Static Site + CMS)
So I’m trying to test this awesome service.
But there was one problem when using the Korean Alphabet.

**Describe the bug**
In the body content, when writing Korean with a space bar, the cursor moves backwards.
So sentences are written backwards.
And written sentences on the editor box in Korean never showed on the preview screen on the right side.

**To Reproduce**
1. Go to site admin  (ex. https://~~~.netlify.app/admin/)
2. Login
3. Click on 'New Blog' Button
4. Write content in Korean alphabet.
 - Title  -> OK
 - Description -> OK
 - Body -> Error
 - Tags -> OK

**Screenshots**
![issues gif](https://ahnslab.com/assets/images/tmp/editbox-Korean-alphabet-issues.gif)

**Comment by martinjagodic** [comment] 2023-06-30 07:14
Hi, @ahnslab this is a known issue. Closing as duplicate of #1347.

**Closed by martinjagodic** 2023-06-30 07:14 UTC
Labels: type: bug
