### ISSUE TITLE
"Media" files don't go through the editorial workflow

### ISSUE THREAD

**Issue by acarnwath** [decaporg/decap-cms#5061] opened 2021-03-05 18:21 UTC
Despite having `publish_mode = 'editorial_workflow';` set (which functions when .md files are created), when an asset is uploaded in the "Media" section, it commits directly to the branch (with the log "Upload “static/assets/file.pdf”) without going through the "approval" (i.e. pull request) process.
This has caused us to inadvertently publish items early since we have automated builds on our master branch.
The expectation would be for these files to follow the same workflow that the .md files do and go through a pull request when `editorial_workflow` is set.

**Comment by erezrokah** [comment] 2021-03-08 11:27
Hi @acarnwath - I don't believe this is a bug, but intended behavior.

Media files **_do go through editorial workflow_** if you upload them when editing an entry.
If you upload them directly via the media modal they will be committed directly to the default branch - that's correct. I'm not sure how approving a single image out of context of a specific entry will work.

Another option to prevent such cases is to allow a configuration to disable the "global" media library.

**Comment by acarnwath** [comment] 2021-03-09 17:03
The use case that we have is that we want to host "hanging" PDFs or images that aren't used by the website, but rather linked to from social media or email, so uploading it through an entry I don't think works.

This might be a particular use case, I'm not sure, but an extra step of approval before pushing this live would be helpful in our case!

**Comment by martinjagodic** [comment] 2023-05-12 13:39
Closing as stale.

**Closed by martinjagodic** 2023-05-12 13:39 UTC
Labels: area: media-library, area: extensions/media-libraries, area: ui/editorial-workflow, status: not a bug
