### ISSUE TITLE
Apply Invalid Styles To Parent(s) of Invalid Field

### ISSUE THREAD

**Issue by Undistraction** [decaporg/decap-cms#3680] opened 2020-04-30 13:56 UTC
Currently if a nested field contains an invalid value when an entry is published, and its parent (or parents) are toggled closed, there is nothing to indicate where the invalid field is. This makes it look as if the publish has simply failed without reason and the only way to diagnose the source of the failure is to toggle open all fields until the invalid field is discovered.

How about marking all parent fields of the invalid field as invalid too. This would provide a nice simple breadcrumb trail to the invalid field(s).

**Comment by AndrewArkwright** [comment] 2022-09-03 01:40
Would it be okay if I grabbed this issue? I’m new to contributing, so any extra tips other than following the readme and contributing markdown info are welcome. I also wanted to verify what the is issue as well. From what I understand, if there is a link tag inside of a paragraph tag and there is some problem with the link, it just does not show the error in the cms unless we toggle open all fields, and then we can see the error, but we want to basically have the parent(s) indicate there is a problem within correct?

**Comment by martinjagodic** [comment] 2024-08-05 07:42
Closing as duplicate of #5630

**Closed by martinjagodic** 2024-08-05 07:42 UTC
Labels: good first issue, status: confirmed, pinned, type: bug
