### ISSUE TITLE
Add default "Users" collection and author widget

### ISSUE THREAD

**Issue by austincondiff** [decaporg/decap-cms#2661] opened 2019-09-08 23:24 UTC
**Is your feature request related to a problem? Please describe.**
It is not very apparent which user created which content. There is no good way to display the authors name, bio, website, socials, etc.

**Describe the solution you'd like**
By default, a "Users" folder collection would exist. Users would only be able to edit their own user entry unless an admin, in which case they would also be able to add new users. This Users collection would mirror users stored in Netlify and their associated User entries would be stored as markdown files so that this data is accessible by the site (except passwords and sensitive data). Developers can the go and configure this collection just like any other collection to add additional fields to it (bio, name, socials , etc.).

Entries of other collections can optionally have an author widget which would default to the currently logged in user. This widget can only be set to other users only by an admin. The widget may even be hidden from non-admins as they are not able to change this field.

**Describe alternatives you've considered**
An "Authors" collection can theoretically be created and a relation field can be added to get this functionality, but this is not a very intuitive solution because it will not default to the user that is logged in and user A who created the entry can select user B as the author regardless of their role.

**Additional context**
This helps the process move along much more smoothly when running blogs with contributors that are not necessarily a part of the organization running the website.

**Comment by erquhart** [comment] 2019-09-10 14:45
The backend services (GitHub, Bitbucket, etc) don't support per directory/file granular permissions, so Netlify CMS couldn't enforce users only editing their own info. We also want to avoid assumptions about content models - many will need this Users concept implemented in this way, but many won't. Instead we want to give developers the tools they need to support their use case.

So back to using a regular collection of users/authors - since we can't do anything about users editing one another's info, the remaining concern is selecting the current user by default, which should be doable. I would imagine a combination of [dynamic default values](#1407) and providing some kind of info about the current user in the data passed to widgets on load.

**Comment by austincondiff** [comment] 2019-09-10 16:33
I understand, we don't want to make assumptions. I don't think we have to though because users have to authenticate to access Netlify CMS, therefore we know that Users exist, it is just a matter of whether developers want to use them in their website. So I think we would just be giving developers the option of tying Netlify users to a collection. Considering your point, it might not even be by default. 

Regarding your comment about not being able to enforce that users not edit others content, we actually can do this, at least within Netlify CMS. We would simply check what the value of the author field is (relation widget pointing to the users collection which is configured to be tied to Netlify users). If it is equal to the current users id/username/email (whatever is used to identify them with), then they can edit/save it if a permission role requirement is set on that collection in `config.yml`.

Point being, all of this would be configurable and no assumption would be made. We are just giving developers the tools they need to configure the CMS in this way, a way that most CMS's currently work.

Many businesses have requirements that demand that no user should be able to edit content that does not belong to them. This kind of requirement cannot be met currently and I believe this can be done despite the limitations we are faced with.

**Comment by erquhart** [comment] 2019-09-10 18:16
The issue is that Netlify CMS runs in the browser - you can't enforce server side security from the browser. Only the backend services themselves can do that, which they don't. We could limit what the CMS UI can do through logic, but the user would be able to use the same token as the browser to do whatever they want.

**Comment by austincondiff** [comment] 2019-09-10 18:51
Yes, that is correct. Technically people could do that. Ideally we would want to have server side validation and security. That being said, it would be at a scale that could be controlled and enforced at the organization level to a degree if that were to occur. Do you see not having that piece not worth exploring this functionality on the front-end?

**Comment by erquhart** [comment] 2019-09-10 20:18
There's a lot of prior discussion in #2, the original Roles issue, but yeah that's the idea - we don't want to give the appearance of roles if they aren't actually being enforced on the server.

**Comment by martinjagodic** [comment] 2023-04-28 11:53
Closing in favor of #2.

**Closed by martinjagodic** 2023-04-28 11:53 UTC
