### ISSUE TITLE
 Cursor Jumps to End of Text Field While Editing Content

### ISSUE THREAD

**Issue by Bilal-Bangash** [decaporg/decap-cms#6867] opened 2023-08-13 10:16 UTC
When editing content, specifically within the body field, the cursor behavior is unpredictable. If I'm editing a paragraph in the middle, the cursor often jumps and places itself at the end of the content, disrupting the editing process.

Steps to Reproduce:

Navigate to the Netlify CMS dashboard.
Open an existing post (or content type) for editing.
Place the cursor in the middle of a paragraph within the body field.
Start typing or editing the content.
Observe the cursor jumping to the end of the field.

Expected Behavior:

The cursor should remain where it was placed, allowing for smooth editing of the content.

**Screenshots**
![Netlify-cms-bug](https://github.com/decaporg/decap-cms/assets/53056567/dfde9c17-04fb-418c-8d31-63f5ec682124)

**Applicable Versions:**
 - Netlify CMS version: [netlify-cms@^2.0.0, netlify-cms-app 2.15.72, netlify-cms-core 2.55.2]
 - Git provider: [Gitlab]
 - OS: [Windows 10]
 - Browser version [Chrome Version 115.0.5790.171 (Official Build) (64-bit)]
 - Node.JS version [18.2.0]
 - NPM version [8.9.0]

**CMS configuration**
`
backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/images
public_folder: /images

collections:  
  - name: "blog"
    label: "Blog"
    folder: "src/data/blog"
    media_folder: ''
    public_folder: ''    
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: Title, name: title, widget: string }  
      - label: Meta Data
        name: meta
        widget: "object"
        fields:
          - {label: Seo Title, name: seoTitle, widget: string}
          - {label: Seo Description, name: seoDescription, widget: string}    
      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'blogcategory'
        search_fields: ['categoryname']
        value_field: 'categoryname'
        display_fields: ['{{categoryname}}']
        multiple: true
      - label: 'Topic'
        name: 'topic'
        widget: 'relation'
        collection: 'blogtopic'
        search_fields: ['title']
        value_field: 'title'
        display_fields: ['{{title}}']
        multiple: false
        required: false
      - label: "Post Author"
        name: "author"
        widget: "relation"
        collection: "authors"
        search_fields: ["firstname"]
        value_field: "firstname"
        display_fields: ["firstname"]
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Featured Image, name: featuredimage, widget: image, required: true }
      - { label: Html, name: html, widget: markdown }      
  - name: "blogcategory"
    label: "Category"
    folder: "src/data/blogcategory"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
       - { label: Name, name: categoryname, widget: string }
  - name: "blogtopic"
    label: "Topics"
    folder: "src/data/blogtopic"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
       - { label: Title, name: title, widget: string }  
  - name: "authors"
    label: "Authors"
    folder: "src/data/authors"
    create: true
    media_folder: ''
    public_folder: ''  
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
       - { label: FirstName, name: firstname, widget: string }
       - { label: Email Address, name: email, widget: string }
       - { label: Picture, name: authorImage, widget: image, required: true }
  
  - label: "Pages"
    name: "pages"
    files:    
      - label: "Home Page"
        name: "home"
        file:  "src/data/pages/home/index.json"   
        media_folder: ''
        public_folder: ''         
        fields:
          - {label: Title, name: title, widget: string}  
          - label: Meta Data
            name: meta
            widget: "object"
            fields:
              - {label: Seo Title, name: seoTitle, widget: string}
              - {label: Seo Description, name: seoDescription, widget: string}
          - label: Hero Section
            name: hero
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Content, name: content, widget: markdown}
              - {label: HeroImage, name: heroImage, widget: image, required: true}
              - {label: First Button Label, name: firstButtonLabel, widget: string}
              - {label: First Button Link, name: firstButtonLink, widget: string}
              - {label: Second Button Label, name: secondButtonLabel, widget: string}
              - {label: Second Button Link, name: secondButtonLink, widget: string}
          - label: Why Us Section
            name: whyus
            widget: "object"
            fields:
              - {label: Why Us Content, name: whyusContent, widget: markdown}
              - {label: Why Us Image, name: whyUsImage, widget: image, required: true}
              - {label: Why Us Image Below Content, name: imageBelowContent, widget: markdown}
          - label: Whose for Section
            name: whosefor
            widget: "object"
            fields:
              - {label: Whose For Content, name: whoseforContent, widget: markdown}
              - {label: Key Details Heading, name: keyDetailsHeading, widget: string}              
              - {
                label: Key Details,
                name: kdetailsmore,
                widget: list,
                fields:
                  [
                    { label: Heading, name: heading, widget: string },
                    { label: Content, name: content, widget: text },
                  ],
              }  
              - {label: Enroll Button Link, name: enrbtnlink, widget: string}            
          - label: Choose Right One
            name: chooserightone
            widget: "object"
            fields:
              - {label: Content, name: content, widget: markdown}
              - {label: Image, name: crImage, widget: image, required: true}
          - label: Key Highlights
            name: keyHighlights
            widget: "list"
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Content, name: content, widget: markdown}
          - label: Why Study with Us Section
            name: whystudywithus
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {label: Short Description, name: shortdesc, widget: markdown}
              - {
                label: Highlights List,
                name: highlightslist,
                widget: list,
                fields:
                  [
                    { label: Heading, name: heading, widget: string },
                    { label: Content, name: content, widget: string },
                    { label: Image, name: hImage, widget: image, required: true}
                  ],
              }
              - {
                label: List Items,
                name: listitems,
                widget: list,
                fields:
                  [
                    { label: Heading, name: heading, widget: string },
                    { label: Content, name: content, widget: string },
                    { label: Image, name: hImage, widget: image, required: true}
                  ],
              }
          - label: What you learn
            name: whatyoulearn
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {
                label: Module List,
                name: modulelist,
                widget: list,
                fields:
                  [
                    { label: Module Name, name: name, widget: markdown },
                    { label: Content, name: content, widget: markdown },
                    { label: Milestone, name: milestone, widget: text}
                  ],
              }
          - label: CTA Section
            name: ctasection
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Button Label, name: buttonLabel, widget: string}
              - {label: Button Link, name: buttonLink, widget: string}
          - label: Supporting Section
            name: supportingsection
            widget: object
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {label: Content, name: content, widget: markdown}
              - {
                label: Supporting Groups,
                name: groups,
                widget: list,
                fields:
                  [
                    { label: Content, name: content, widget: string },
                    { label: Image, name: gImage, widget: image, required: true}
                  ],
              }
              - {
                label: Team Members,
                name: teammembers,
                widget: list,
                fields:
                  [
                    { label: Name, name: name, widget: string},
                    { label: Designation, name: designation, widget: string},
                    { label: Content, name: content, widget: text},
                    { label: Picture, name: memberImage, widget: image , required: true}
                  ],
              }
          - label: How Online Learning Words Section
            name: howonline
            widget: object
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {label: Short Description, name: shortdesc, widget: string}
              - { label: Image, name: onImage, widget: image, required: true}
              - {
                label: Hightlight Points,
                name: highlightpoints,
                widget: list,
                fields:
                  [
                    { label: Heading, name: heading, widget: string },
                    { label: Content, name: content, widget: markdown },
                  ],
              }
              - {
                label: Tools,
                name: tools,
                widget: list,
                fields:
                  [
                    { label: Name, name: name, widget: string },
                  ],
              }
      - label: "About Course Page"
        name: "about"
        file:  "src/data/pages/about/index.json"
        media_folder: ''
        public_folder: ''    
        fields:
        - {label: Title, name: title, widget: string}   
        - label: Meta Data
          name: meta
          widget: "object"
          fields:
            - {label: Seo Title, name: seoTitle, widget: string}
            - {label: Seo Description, name: seoDescription, widget: string}    
        - label: Hero Section
          name: hero
          widget: "object"
          fields:
            - {label: Heading, name: heading, widget: string}
            - {label: Content, name: content, widget: markdown}
            - {label: HeroImage, name: heroImage, widget: image, required: true}
            - {
                label: List items,
                name: listItems,
                widget: list,
                required: true,
                fields:
                  [
                    { label: Content, name: content, widget: string, required: true },
                    {label: Image, name: listIcon, widget: image, required: true}
                  ],
              }
        - label: Master Programe Section
          name: masterProgram
          widget: "object"
          fields:
            - {label: Heading, name: heading, widget: markdown}
            - {
                label: List items,
                name: listItems,
                widget: list,
                fields:
                  [
                    { label: Content, name: content, widget: string },
                    {label: Image, name: listIcon, widget: image, required: true}
                  ],
              }
        - label: Who Enroll Section
          name: whoEnroll
          widget: "object"
          fields:
            - { label: Heading, name: heading, widget: markdown}
            - { label: Content, name: content, widget: markdown}
            - { label: Image above Heading, name: iaboveHeading, widget: string }
            - { label: Image above conent, name: iaboveContent, widget: string }
            - {label: Image, name: image, widget: image, required: true}
            - {
                label: List items,
                name: listItems,
                widget: list,
                fields:
                  [
                    { label: Content, name: content, widget: string }
                  ],
              }
        - label: Learning Path Section
          name: learningPath
          widget: "object"
          fields:
            - { label: Heading, name: heading, widget: markdown}
            - {label: Image, name: image, widget: image, required: true}
            - { label: Key Areas Heading, name: keyareasHeading, widget: string}
            - {
              label: List items,
              name: listItems,
              widget: list,
              fields:
                [
                  { label: Content, name: content, widget: string }
                ],
            }
            - {label: Second Button Label, name: secondButtonLabel, widget: string}
            - {label: Second Button Link, name: secondButtonLink, widget: string}
        - label: Delivered Digitally Section
          name: deliveredDigitally
          widget: "object"
          fields:
            - { label: Heading, name: heading, widget: markdown}
            - { label: Image, name: image, widget: image}
            - {
              label: Start List item,
              name: listItems,
              widget: list,
              fields:
                [
                  { label: Content, name: content, widget: string }
                ],
            }
        - label: Certified Business Section
          name: certifiedBusiness
          widget: "object"
          fields:
            - { label: Heading, name: heading, widget: markdown}
            - { label: Endorsed Text, name: endorsedLabel, widget: string}
            - { label: Endorsed Image, name: endorsedimage, widget: image}
            - { label: Content, name: content, widget: markdown}
            - { label: Image, name: image, widget: image, required: true}
            - { label: Key Learning Heading, name: keyLearningHeading, widget: string}
            - {
              label: Key Learning List,
              name: keylearninglist,
              widget: list,
              fields:
                [
                  { label: Content, name: content, widget: string }
                ],
            }
        - label: Course curriculum Section
          name: courseCurriculum
          widget: "object"
          fields:
            - { label: Heading, name: heading, widget: string}
            - { label: Image, name: image, widget: image, required: true}
            - {
              label: Lessons List,
              name: lessonslistItems,
              widget: list,
              fields:
                [
                  { label: Content, name: content, widget: string }
                ],
            }
        - label: Capstone Section
          name: capstone
          widget: "object"
          fields:
            - { label: Heading, name: heading, widget: markdown}
            - {
              label: Highlights List,
              name: highlightslistItems,
              widget: list,
              fields:
                [
                  { label: Content, name: content, widget: string }
                ],
            }
            - { label: Sub Heading, name: subheading, widget: string}
            - {
              label: List Items,
              name: listItems,
              widget: list,
              fields:
                [
                  { label: Title, name: title, widget: string},
                  { label: Content, name: content, widget: string}
                ],
            }
        - label: Tools and Services Section
          name: toolsServices
          widget: "object"
          fields:
            - { label: Heading, name: heading, widget: markdown}
            - { label: Image, name: image, widget: image, required: true}
            - {
              label: Tools List,
              name: toolslistItems,
              widget: list,
              fields:
                [
                  { label: Name, name: name, widget: string},
                  { label: Logo Image, name: logo, widget: image, required: true}
                ],
            }
        - label: Program Endorsed Section
          name: programEndorsed
          widget: "object"
          fields:
            - { label: Heading, name: heading, widget: string}
            - { label: Logo Image, name: logoimage, widget: image, required: true}
            - { label: Image, name: image, widget: image, required: true}
            - { label: Content, name: content, widget: markdown}
      - label: "Enroll Page"
        name: "enroll"
        media_folder: ''
        public_folder: ''    
        file:  "src/data/pages/enroll/index.json"  
        fields:
          - {label: Title, name: title, widget: string}   
          - label: Meta Data
            name: meta
            widget: "object"
            fields:
              - {label: Seo Title, name: seoTitle, widget: string}
              - {label: Seo Description, name: seoDescription, widget: string}
          - label: Hero Section
            name: hero
            widget: "object"
            fields:
              - {label: Short Heading, name: shortHeading, widget: string}
              - {label: Heading, name: heading, widget: string, required: true}
              - {label: Button Label, name: ButtonLabel, widget: string, required: true}
              - {label: Button Link, name: ButtonLink, widget: string, required: true}
              - {label: Industry Partners Label, name: industryPartnersLabel, widget: string, required: true}
              - {
                label: Industry Partners List,
                name: partnerslistItems,
                widget: list,
                fields:
                  [
                    { label: Logo Image, name: logo, widget: image, required: true}
                  ],
                }
          - label: Short Course Details
            name: coursedetails
            widget: "object"
            fields:
              - {label: Description, name: description, widget: text}
              - {label: Next Start Date 1, name: startDate1, widget: date}
              - {label: Next Start Date 2, name: startDate2, widget: date}
              - {label: Next Start Date 3, name: startDate3, widget: date}
              - {label: Next Start Date 4, name: startDate4, widget: date}
              - {label: Prerequisites, name: prerequisites, widget: string}
              - {label: Time Commitment, name: timeCommitment, widget: string}
              - {label: First Button Label, name: firstButtonLabel, widget: string}
              - {label: First Button Link, name: firstButtonLink, widget: string}
              - {label: Second Button Label, name: secondButtonLabel, widget: string}
              - {label: Second Button Link, name: secondButtonLink, widget: string}             
          - label: LevelUp Skills Section
            name: levelUpSkills
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {label: Short Text, name: shortText, widget: string}
              - {label: Content, name: content, widget: markdown}
              - {label: Why This Course Content, name: whyThisCourseContent, widget: markdown}
              - {label: Button Label, name: firstButtonLabel, widget: string}
              - {label: Button Link, name: firstButtonLink, widget: string}
          - label: Course Structure Section
            name: courseStructure
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {
                label: Module List,
                name: modulelist,
                widget: list,
                fields:
                  [
                    { label: Module Name, name: name, widget: markdown },
                    { label: Content, name: content, widget: markdown },
                    { label: Milestone, name: milestone, widget: text}
                  ],
                }
          - label: FAQ Section
            name: faq
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {label: Short Text, name: shortText, widget: string}
              - {
                label: FAQ Categores,
                name: faqcategories,
                widget: list,
                fields:
                  [
                    { label: Category Name, name: categoryName, widget: string},
                    {
                      label: FAQ List,
                      name: faqlist,
                      widget: list,
                      fields:
                        [
                          { label: Question, name: question, widget: string },
                          { label: Answer, name: answer, widget: markdown }
                        ],
                    }     
                  ],
                }
          - label: Industry Experts Section
            name: industryExperts
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {
                label: Team Members,
                name: teammembers,
                widget: list,
                fields:
                  [
                    { label: Name, name: name, widget: string},
                    { label: Designation, name: designation, widget: string},
                    { label: Content, name: content, widget: markdown},
                    { label: Picture, name: memberImage, widget: image, required: true}
                  ],
                }
      - label: "Mentors Page"
        name: "mentors"
        file:  "src/data/pages/mentors/index.json" 
        media_folder: ''
        public_folder: ''          
        fields:
          - {label: Title, name: title, widget: string}  
          - label: Meta Data
            name: meta
            widget: "object"
            fields:
              - {label: Seo Title, name: seoTitle, widget: string}
              - {label: Seo Description, name: seoDescription, widget: string}
          - label: Hero Section
            name: hero
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Content, name: content, widget: markdown}
              - {label: HeroImage, name: heroImage, widget: image, required: true}
              - {label: First Button Label, name: firstButtonLabel, widget: string}
              - {label: First Button Link, name: firstButtonLink, widget: string}
              - {label: Second Button Label, name: secondButtonLabel, widget: string}
              - {label: Second Button Link, name: secondButtonLink, widget: string}
          - label: Mentorship Section
            name: mentorship
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {label: Content, name: content, widget: markdown}
              - {label: Mentor Will Do Text, name: mentorwilldo, widget: string}
              - {
                label: List item,
                name: listItems,
                widget: list,
                fields:
                  [
                    { label: Content, name: content, widget: string }
                  ],
                }
          - label: Technology Partner Section
            name: technologyPartner
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {label: Content, name: content, widget: markdown}
              - {
                label: Partners List,
                name: partners,
                widget: list,
                fields:
                  [
                    { label: Name, name: name, widget: string},
                    { label: Designation, name: designation, widget: string},
                    { label: Picture, name: memberImage, widget: image, required: true},
                    { label: Company Logo, name: logoImage, widget: image, required: true},
                    { label: Instagram Link, name: instagram, widget: string },
                    { label: Facebook Link, name: facebook, widget: string },
                    { label: Linkedin Link, name: linkedin, widget: string }
                  ],
                }
          - label: Matching with Mentor Section
            name: matchingwithMentor
            widget: "object"
            fields:
              - {label: Heading, name: heading, widget: markdown}
              - {label: Content, name: content, widget: markdown}
              - {
                  label: FAQ List,
                  name: faqlist,
                  widget: list,
                  fields:
                    [
                      { label: Question, name: question, widget: string },
                      { label: Answer, name: answer, widget: markdown }
                    ],
                }  
              - {
                label: Mentor Details,
                name: mentorDetails,
                widget: object,
                fields:
                  [
                    { label: Name, name: name, widget: string},
                    { label: Designation, name: designation, widget: string},
                    { label: Picture, name: memberImage, widget: image, required: true},
                    { label: Testimonial, name: testimonial, widget: text},
                  ],
                }
      - label: "Blog Page"
        name: "blogpage"
        file:  "src/data/pages/blog/index.json"   
        media_folder: ''
        public_folder: ''         
        fields:
          - {label: Title, name: title, widget: string} 
          - {label: Description, name: description, widget: markdown} 
          - label: Meta Data
            name: meta
            widget: "object"
            fields:
              - {label: Seo Title, name: seoTitle, widget: string}
              - {label: Seo Description, name: seoDescription, widget: string}
      - label: "Signup Page"
        name: "signuppage"
        file:  "src/data/pages/signup/index.json"  
        fields:
          - {label: Title, name: title, widget: markdown} 
          - {label: Description, name: description, widget: text} 
          - label: Meta Data
            name: meta
            widget: "object"
            fields:
              - {label: Seo Title, name: seoTitle, widget: string}
              - {label: Seo Description, name: seoDescription, widget: string}
      - label: "Contact Page"
        name: "contactpage"
        file:  "src/data/pages/contact/index.json"  
        fields:
          - {label: Title, name: title, widget: markdown} 
          - {label: Description, name: description, widget: text} 
          - {label: Email Address, name: email, widget: string} 
          - {label: Phone Number, name: phone, widget: string}  
          - {label: Address, name: address, widget: string} 
          - {label: Instagram Link, name: instagram, widget: string} 
          - {label: Twitter Link, name: twitter, widget: string} 
          - {label: Facebook Link, name: facebook, widget: string} 
          - {label: LinkedIn Link, name: linkedin, widget: string} 
          - {label: Form Heading, name: heading, widget: markdown} 
          - {label: Form Sub Heading, name: subheading, widget: text} 
          - label: Meta Data
            name: meta
            widget: "object"
            fields:
              - {label: Seo Title, name: seoTitle, widget: string}
              - {label: Seo Description, name: seoDescription, widget: string}
  - label: "Widgets"
    name: "widgets"
    files:    
      - label: "Enrolment"
        name: "enrol"
        file:  "src/data/widgets/enrol/index.json"   
        media_folder: ''
        public_folder: ''     
        fields:
          - { label: Heading, name: heading, widget: string}  
          - { label: Content, name: content, widget: markdown}
          - { label: Image, name: eImage, widget: image, required: true}
          - { label: Button Label, name: buttonLabel, widget: string} 
          - { label: Button Link, name: buttonLink, widget: string}    
`

**Notes:**

I've attempted to diagnose this issue by:

1. Opening the CMS in an incognito window to rule out browser extension interference.
2. Checking for JavaScript errors in the browser console (none were found).

Would appreciate any insights or assistance!

**Comment by fool** [comment] 2023-08-13 19:32
probably a duplicate of https://github.com/decaporg/decap-cms/issues/5092

**Comment by martinjagodic** [comment] 2023-08-16 07:29
Closing as duplicate of #5092

**Closed by martinjagodic** 2023-08-16 07:29 UTC
Labels: type: bug
