### ISSUE TITLE
Issues using Git after installing Netlify Large Media

### ISSUE THREAD

**Issue by jeremyzilar** [decaporg/decap-cms#3711] opened 2020-05-07 03:42 UTC
We are trying to migrate the **Brooklyn Rail** to Netlify + NetlifyCMS and one of the early snags we are running into is with setting up Netlify Large Media + Git-LFS to manage the media in the repo. 

The issue is that after installing all of the required elements, we are no longer able to commit back to GitHub 😬

**Specifically,** 
- not able to push or pull using GitHub in the terminal when the remote path is set to `https://github.com/brooklynrail/brooklynrail-platform.git`. But we are able to push and pull when the remote is set to `git@github.com:brooklynrail/brooklynrail-platform.git`, though it asks for our SSH key password _twice_ before pulling/pushing.
- not able to push or pull using GitHub Desktop, both when the remote path is set to `https://github.com/brooklynrail/brooklynrail-platform.git` or `git@github.com:brooklynrail/brooklynrail-platform.git`.

_(note, this seems to only affect this repo, and this branch)_

![image](https://user-images.githubusercontent.com/395641/81251163-a61c0a80-8ff0-11ea-99d8-bdefef85457a.png)

If you are interested in looking at :eyes: our NetlifyCMS config, it can be found at `/themes/brooklynrail/static/workflow`

## What have we tried?
- re-installing everything
- following a lot of troubleshooting advice here https://piperhaywood.com/configuring-and-troubleshooting-netlify-large-media/

I ran `git config --list --show-origin` to help with any debugging. Here is what I got:

```
jeremy@Field-Work brooklynrail-platform % git config --list --show-origin
file:/usr/local/etc/gitconfig   credential.helper=osxkeychain
file:/usr/local/etc/gitconfig   filter.lfs.clean=git-lfs clean -- %f
file:/usr/local/etc/gitconfig   filter.lfs.smudge=git-lfs smudge -- %f
file:/usr/local/etc/gitconfig   filter.lfs.process=git-lfs filter-process
file:/usr/local/etc/gitconfig   filter.lfs.required=true
file:/Users/jeremy/.gitconfig   filter.lfs.process=git-lfs filter-process
file:/Users/jeremy/.gitconfig   filter.lfs.required=true
file:/Users/jeremy/.gitconfig   filter.lfs.clean=git-lfs clean -- %f
file:/Users/jeremy/.gitconfig   filter.lfs.smudge=git-lfs smudge -- %f
file:/Users/jeremy/.gitconfig   user.name=Jeremy Zilar
file:/Users/jeremy/.gitconfig   user.email=jeremyzilar@gmail.com
file:/Users/jeremy/.gitconfig   include.path=/Users/jeremy/.netlify/helper/git-config
file:/Users/jeremy/.netlify/helper/git-config   credential.helper=
file:/Users/jeremy/.netlify/helper/git-config   credential.usehttppath=true
file:/Users/jeremy/.netlify/helper/git-config   credential.helper=netlify
file:/Users/jeremy/.netlify/helper/git-config   credential.helper=osxkeychain
file:.git/config        core.repositoryformatversion=0
file:.git/config        core.filemode=true
file:.git/config        core.bare=false
file:.git/config        core.logallrefupdates=true
file:.git/config        core.ignorecase=true
file:.git/config        core.precomposeunicode=true
file:.git/config        submodule.active=.
file:.git/config        remote.origin.url=git@github.com:brooklynrail/brooklynrail-platform.git
file:.git/config        remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
file:.git/config        branch.master.remote=origin
file:.git/config        branch.master.merge=refs/heads/master
file:.git/config        branch.pa11y.remote=origin
file:.git/config        branch.pa11y.merge=refs/heads/pa11y
file:.git/config        branch.hugo_env.remote=origin
file:.git/config        branch.hugo_env.merge=refs/heads/hugo_env
file:.git/config        branch.cms/authors/jeremy/_index.remote=origin
file:.git/config        branch.cms/authors/jeremy/_index.merge=refs/heads/cms/authors/jeremy/_index
file:.git/config        lfs.https://db6c835f-87e3-47c4-8f4d-53b4af3c6be8.netlify.app/.netlify/large-media.access=basic
file:.git/config        lfs.https://db6c835f-87e3-47c4-8f4d-53b4af3c6be8.netlify.app/.netlify/large-media.locksverify=false
file:.git/config        credential.helper=netlify
file:.git/config        lfs.https://github.com/brooklynrail/brooklynrail-platform.git/info/lfs.access=basic
file:.git/config        branch.images.remote=origin
file:.git/config        branch.images.merge=refs/heads/images
file:.git/config        branch.media-cms-fix.remote=origin
file:.git/config        branch.media-cms-fix.merge=refs/heads/media-cms-fix
````

**Also**
- Still unsure if we need to be using Git Gateway with Netlify to get this set up. 
- If so, do we need [netlify-identity-widget](https://github.com/netlify/netlify-identity-widget) as part of the identity set up? If so, why is it not mentioned here?

**Comment by erezrokah** [comment] 2020-05-07 07:45
Thanks for reporting @jeremyzilar, I'll try setting this up and see if I have the same issues.
To use Large Media with the CMS you do need to configure it with `git-gateway` and Identity since the CMS uses the Identity access token to access the Large Media service.
The Identity widget is needed to facilitate authentication with Identity. Is [this](https://www.netlifycms.org/docs/git-gateway-backend/#git-gateway-with-netlify-identity) the place in the docs we should mention it?

**Comment by erezrokah** [comment] 2020-05-07 14:02
Linking https://community.netlify.com/t/common-issue-troubleshooting-your-netlify-large-media-configuration/188 for more information

**Comment by jeremyzilar** [comment] 2020-05-07 17:23
Thanks @erezrokah, I am going through the git-gateway setup now, and will take notes on the steps to set it up. I will also start a new issue around any bits of confusion with Git-Gateway and Identity _(since that is a separate topic)_ https://github.com/netlify/netlify-cms/issues/3718

**Comment by jeremyzilar** [comment] 2020-05-07 17:54
From this [troubleshooting guide](https://community.netlify.com/t/common-issue-troubleshooting-your-netlify-large-media-configuration/188), I ran `netlify lm:info` and got
```
jeremy@Field-Work brooklynrail-platform % netlify lm:info
  ✔ Checking Git version [2.22.0]
  ✔ Checking Git LFS version [2.10.0]
  ✔ Checking Git LFS filters
  ✔ Checking Netlify's Git Credentials version [0.1.9]
```

### What I did
1. I double-checked that I had Netlify CLI installed, and I [ran the global install found here](https://docs.netlify.com/cli/get-started/#installation) `npm install netlify-cli -g`
1. Updated netlify-cli in my local repo `npm i netlify-cli`
1. Ran `netlify init` to ensure that my local repo is connected

**Comment by jeremyzilar** [comment] 2020-05-07 18:16
Now onto getting the Git Gateway setup and working...

**Comment by jeremyzilar** [comment] 2020-05-10 12:25
Without a doubt, there are still issues with using GIT after installing LFS and getting this setup :/
Especially when trying to collaborate with others and merge in changes. I will try to document the steps and the specific issues.

**Comment by jeremyzilar** [comment] 2020-05-11 00:06
@erezrokah this is the specific issue I am getting:
![image](https://user-images.githubusercontent.com/395641/81513780-ec2ae400-92f8-11ea-9b2c-2d1956c58cd2.png)
```
batch response: Post https://db6c835f-87e3-47c4-8f4d-53b4af3c6be8.netlify.app/.netlify/large-media/objects/batch: dial tcp: lookup db6c835f-87e3-47c4-8f4d-53b4af3c6be8.netlify.app: no such host
error: failed to push some refs to 'https://github.com/brooklynrail/brooklynrail-platform.git'
```

This thread on GIT-LFS issues seems relevant https://github.com/git-lfs/git-lfs/issues/2887
Still looking...

**Comment by overlordofmu** [comment] 2020-05-14 07:27
Hi, @jeremyzilar, as mentioned in the Git LFS issue thread (`git-lfs/git-lfs#2887`), this looks like a DNS resolution issue.

The domain name in this case works for me when I test:

```text
$ nslookup db6c835f-87e3-47c4-8f4d-53b4af3c6be8.netlify.app
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	db6c835f-87e3-47c4-8f4d-53b4af3c6be8.netlify.app
Address: 138.68.244.143
```

Would you be willing to test the same command on the affected system if the issue is still occurring? That command being:

```text
nslookup db6c835f-87e3-47c4-8f4d-53b4af3c6be8.netlify.app
```

The the DNS lookup fails locally, that is the root cause of the error above. If you do get local DNS errors we'll be happy to troubleshoot to find out why and resolve it.

**Comment by martinjagodic** [comment] 2024-08-05 07:48
Closing as not planned because Netlify Large Media is sadly deprecated

**Closed by martinjagodic** 2024-08-05 07:48 UTC
Labels: type: bug, status: unconfirmed, area: large media (lfs)
