### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child o...

### ISSUE THREAD

**Issue by alextbok** [decaporg/decap-cms#7244] opened 2024-07-01 15:56 UTC
**Describe the bug**
I get an error toast as well as a long error body rendered directly into the dom. I am using `CMS.init` and mounting to a nested div (via `<div id="nc-root" />`), but fwiw, I see the same error when using the default mount.

**To Reproduce**
Happy to provide more details if needed.

**Expected behavior**
To not show the error.

**Screenshots**
<img width="577" alt="Screenshot 2024-07-01 at 11 52 51 AM" src="https://github.com/decaporg/decap-cms/assets/6645104/b6d3077f-04c8-41d0-85b0-5ca8eeba5ab5">

**Applicable Versions:**
 - Decap CMS version: `decap-cms-app@3.1.11`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36`

**CMS configuration**
```
media_folder: apps/www/public/media
public_folder: /assets/media
site_url: localhost:3500
publish_mode: editorial_workflow
collections:
  - name: core
    label: Core
    files:
      - label: Home
        name: home
        file: apps/www/src/content/core/home.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: About Us
        name: about-us
        file: apps/www/src/content/core/about-us.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
    publish: true
    type: file_based_collection
    sortable_fields:
      - commit_date
      - commit_author
    view_filters: []
    view_groups: []
    editor:
      preview: false
  - name: blog
    label: Blog
    folder: apps/www/src/content/blog
    create: true
    format: frontmatter
    extension: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Featured Image
        name: featured-image
        widget: image
      - label: Publish Date
        name: publish-date
        widget: datetime
      - label: Tags
        name: tags
        widget: list
        default: []
      - label: Author
        name: author
        widget: string
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - author
    view_filters: []
    view_groups: []
    editor:
      preview: false
backend:
  name: github
  auth_scope: repo
  auth_type: implicit
  auth_endpoint: /install/auth
  repo: americantraveler/atsp
  branch: bok/decap
  base_url: /internal/cms
  squash_merges: true
  commit_messages:
    create: "[cms] ({{author-name}}) Create {{path}}"
    update: "[cms] ({{author-name}}) Update {{path}}"
    delete: "[cms] ({{author-name}}) Delete {{path}}"
    uploadMedia: "[cms] ({{author-name}}) Upload {{path}}"
    deleteMedia: "[cms] ({{author-name}}) Delete {{path}}"
    openAuthoring: "[cms] ({{author-name}}) {{message}}"
  site_domain: localhost:3500
load_config_file: false
editor:
  preview: false
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "-"
display_url: localhost:3500
isFetching: false
error: null

```

**Additional context**
Full error stack:
```
removeChildFromContainer
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (35690:1)
commitDeletionEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22106:1)
commitDeletionEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22013:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22413:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22488:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22449:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22449:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22488:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22488:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22488:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22449:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22449:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22449:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22449:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22876:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22449:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22449:1)
recursivelyTraverseMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22427:1)
commitMutationEffectsOnFiber
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22681:1)
commitMutationEffects
../../node_modules/next/dist/compiled/react-dom/cjs/react-dom.development.js (22397:1)
```

**Comment by martinjagodic** [comment] 2024-08-05 08:09
Duplicate of #6965

**Closed by martinjagodic** 2024-08-05 08:09 UTC
