### ISSUE TITLE
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child o...

### ISSUE THREAD

**Issue by gxanshu** [decaporg/decap-cms#7119] opened 2024-02-24 10:39 UTC
**Describe the bug**
I opened the admin area as usual but this time i'm getting an error 
**To Reproduce**

**Expected behavior**
Site should be opened correctly  

**Screenshots**
![image](https://github.com/decaporg/decap-cms/assets/68537640/d03eeb1d-a3f0-4a89-afe6-e007075c9f05)

**Applicable Versions:**
 - Decap CMS version: `decap-cms@3.1.2`
 - Git provider: `github`
 - Browser version: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36`

**CMS configuration**
```
backend:
  name: github
  repo: gxanshu/gxanshu-site
  branch: main
  base_url: https://gxanshu.in
  auth_endpoint: /api/auth
  squash_merges: true
  auth_scope: repo
  open_authoring: true
publish_mode: editorial_workflow
media_folder: public/assets
public_folder: /assets
site_url: https://gxanshu.in
collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    create: true
    extension: mdx
    format: frontmatter
    preview_path: blog/{{slug}}
    fields:
      - name: title
        label: Title
      - name: description
        label: Description
      - label: Date
        name: pubDate
        widget: datetime
        default: ""
        date_format: YYYY.MM.DD
        time_format: false
        format: LLL
        picker_utc: false
      - label: Image
        name: image
        widget: image
        choose_url: true
        media_library:
          config:
            multiple: false
      - name: body
        label: Body
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - commit_author
      - description
    view_filters: []
    view_groups: []
  - name: notes
    label: Notes
    folder: src/content/notes
    create: true
    extension: mdx
    format: frontmatter
    preview_path: notes/{{slug}}
    fields:
      - name: title
        label: Title
      - name: description
        label: Description
      - label: Date
        name: pubDate
        widget: datetime
        default: ""
        date_format: YYYY.MM.DD
        time_format: false
        format: LLL
        picker_utc: false
      - name: body
        label: Body
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - commit_author
      - description
    view_filters: []
    view_groups: []
  - name: projects
    label: Projects
    folder: src/content/projects
    create: true
    extension: mdx
    format: frontmatter
    preview_path: projects/{{slug}}
    fields:
      - name: heading
        label: heading
      - name: title
        label: Title
      - name: description
        label: Description
      - label: Date
        name: pubDate
        widget: datetime
        default: ""
        date_format: YYYY.MM.DD
        time_format: false
        format: LLL
        picker_utc: false
      - label: Status
        name: status
        widget: select
        options:
          - active
          - inactive
        default: active
      - label: Logo
        name: logo
        widget: image
        choose_url: true
        media_library:
          config:
            multiple: false
      - name: author
        label: Author
      - label: Tech Stacks
        name: techStack
        widget: list
        default:
          - typescript-plain
      - name: body
        label: Body
        widget: markdown
    publish: true
    type: folder_based_collection
    sortable_fields:
      - commit_date
      - title
      - author
      - description
    view_filters: []
    view_groups: []
slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: "-"
display_url: https://gxanshu.in
isFetching: false
error: null

```

**Additional context**

**Comment by martinjagodic** [comment] 2024-02-26 07:14
Closing as duplicate of #7106

**Closed by martinjagodic** 2024-02-26 07:14 UTC
